language: cpp
compiler: g++

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-5
  - export CXX="g++-5"

script:
  - cd test
  - make || exit 1
  - cd ../
  - doxygen Doxyfile

addons:
  apt:
    packages:
      - doxygen

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: main
